// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Core__Option = require("@rescript/core/src/Core__Option.bs.js");

var mustLoad = [
  "Platform",
  "CosmosAsync",
  "showNotification",
  "ContextMenu"
];

while(mustLoad.map(function (prop) {
          return Spicetify[prop];
        }).some(Core__Option.isNone)) {
  await new Promise((function (res, param) {
          setTimeout((function (param) {
                  res(undefined);
                }), 100);
        }));
};

function spotUriTypeToString(spotUriType) {
  var tmp;
  switch (spotUriType) {
    case /* ALBUM */0 :
        tmp = "album";
        break;
    case /* ARTIST */1 :
        tmp = "artist";
        break;
    case /* PLAYLIST */2 :
        tmp = "playlist";
        break;
    case /* TRACK */3 :
        tmp = "track";
        break;
    
  }
  return "spotify:" + tmp;
}

function showIn(spotUriTypes, param) {
  var spotUri = param[0];
  return spotUriTypes.map(spotUriTypeToString).some(function (param) {
              return spotUri.startsWith(param);
            });
}

async function fetchPlaylistEnhancedSongs100(offsetOpt, spotUri) {
  var offset = offsetOpt !== undefined ? offsetOpt : 0;
  return (await Curry._1(Spicetify.CosmosAsync.get, "https://spclient.wg.spotify.com/enhanced-view/v1/context/" + spotUri + "?&offset=" + offset.toString() + "&format=json")).pageItems;
}

async function fetchPlaylistEnhancedSongs(offsetOpt, spotUri) {
  var offset = offsetOpt !== undefined ? offsetOpt : 0;
  var nextItems = await fetchPlaylistEnhancedSongs100(offset, spotUri);
  if (nextItems.length < 100) {
    return nextItems;
  } else {
    return nextItems.concat(await fetchPlaylistEnhancedSongs(offset + 100 | 0, spotUri));
  }
}

function playEnhancedSongs(param) {
  fetchPlaylistEnhancedSongs(undefined, param[0]).then(function (queue) {
        Curry._1(Spicetify.Platform.PlayerAPI.clearQueue, undefined);
        return Curry._1(Spicetify.Platform.PlayerAPI.addToQueue, queue);
      });
}

var partial_arg = [/* PLAYLIST */2];

new Spicetify.ContextMenu.Item("Play Enhanced Songs", playEnhancedSongs, (function (param) {
        return showIn(partial_arg, param);
      }), "enhance");

exports.mustLoad = mustLoad;
exports.spotUriTypeToString = spotUriTypeToString;
exports.showIn = showIn;
exports.fetchPlaylistEnhancedSongs100 = fetchPlaylistEnhancedSongs100;
exports.fetchPlaylistEnhancedSongs = fetchPlaylistEnhancedSongs;
exports.playEnhancedSongs = playEnhancedSongs;
/*  Not a pure module */
